package com.greymatter.miner.enums;

public enum MatId {
    GROUND_MATERIAL,
    HARMAN,
    DIALOG_MATERIAL,
    ATMOSPHERE_MATERIAL,
    MAIN_BASE_MATERIAL,
    PLANET_GRASS_MATERIAL_I,
    TREE_MATERIAL,
    GRADIENT_COLOR_MATERIAL,
    BUTTON_MATERIAL_I
}
