package com.greymatter.miner.loaders.enums;

public enum Tag {
    PLACABLE_GAME_BUILDING,
    PLACABLE_GAME_OBJECT,
    STATIC,
    GAME_LIGHT,
    PHYSICS_OBJECT,
    STATIC_PHYSICS_OBJECT,
    DYNAMIC_PHYSICS_OBJECT,
    RESOURCE_OBJECT,
    NOTIFICATION,
    DIALOG,
    SIGNAL,
    UI_OBJECT
}
